#ifndef UDEMY_BIBLE_COMP_PROG_EXAMPLES_SIEVE_OF_ERATOSTHENES_H
#define UDEMY_BIBLE_COMP_PROG_EXAMPLES_SIEVE_OF_ERATOSTHENES_H

void sieveOfEratosthenes(bool pBoolean [5]){

}

#endif  // UDEMY_BIBLE_COMP_PROG_EXAMPLES_SIEVE_OF_ERATOSTHENES_H
